/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myproject.pocketclinic;

/**
 *
 * @author Souvik Das
 */

public class JFrame_Home extends javax.swing.JFrame
{

    /**
     * Creates new form JFrame_Home
     */
    public JFrame_Home()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane_Home = new javax.swing.JTabbedPane();
        jTabbedPane_Search = new javax.swing.JTabbedPane();
        jPanel_Search_User = new javax.swing.JPanel();
        jPanel_Search_Case = new javax.swing.JPanel();
        jTabbedPane_Profile = new javax.swing.JTabbedPane();
        jPanel_Profile_Patient = new javax.swing.JPanel();
        jPanel_Profile_Doctor = new javax.swing.JPanel();
        jPanel_Profile_Settings = new javax.swing.JPanel();
        jPanel_Cases = new javax.swing.JPanel();
        jTabbedPane_Cases = new javax.swing.JTabbedPane();
        jPanel_Cases_Active = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_Cases_Closed = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_Cases_Open = new javax.swing.JButton();
        jButton_Cases_Add = new javax.swing.JButton();
        jPanel_Predict = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel_Ranking = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel_NearbyPlaces = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_Home.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane_Home.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jTabbedPane_Home.setMaximumSize(new java.awt.Dimension(600, 400));
        jTabbedPane_Home.setMinimumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanel_Search_UserLayout = new javax.swing.GroupLayout(jPanel_Search_User);
        jPanel_Search_User.setLayout(jPanel_Search_UserLayout);
        jPanel_Search_UserLayout.setHorizontalGroup(
            jPanel_Search_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Search_UserLayout.setVerticalGroup(
            jPanel_Search_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Search.addTab("Search User", jPanel_Search_User);

        javax.swing.GroupLayout jPanel_Search_CaseLayout = new javax.swing.GroupLayout(jPanel_Search_Case);
        jPanel_Search_Case.setLayout(jPanel_Search_CaseLayout);
        jPanel_Search_CaseLayout.setHorizontalGroup(
            jPanel_Search_CaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Search_CaseLayout.setVerticalGroup(
            jPanel_Search_CaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Search.addTab("Search Case", jPanel_Search_Case);

        jTabbedPane_Home.addTab("Search", jTabbedPane_Search);

        javax.swing.GroupLayout jPanel_Profile_PatientLayout = new javax.swing.GroupLayout(jPanel_Profile_Patient);
        jPanel_Profile_Patient.setLayout(jPanel_Profile_PatientLayout);
        jPanel_Profile_PatientLayout.setHorizontalGroup(
            jPanel_Profile_PatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_PatientLayout.setVerticalGroup(
            jPanel_Profile_PatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Patient", jPanel_Profile_Patient);

        javax.swing.GroupLayout jPanel_Profile_DoctorLayout = new javax.swing.GroupLayout(jPanel_Profile_Doctor);
        jPanel_Profile_Doctor.setLayout(jPanel_Profile_DoctorLayout);
        jPanel_Profile_DoctorLayout.setHorizontalGroup(
            jPanel_Profile_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_DoctorLayout.setVerticalGroup(
            jPanel_Profile_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Doctor", jPanel_Profile_Doctor);

        javax.swing.GroupLayout jPanel_Profile_SettingsLayout = new javax.swing.GroupLayout(jPanel_Profile_Settings);
        jPanel_Profile_Settings.setLayout(jPanel_Profile_SettingsLayout);
        jPanel_Profile_SettingsLayout.setHorizontalGroup(
            jPanel_Profile_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_SettingsLayout.setVerticalGroup(
            jPanel_Profile_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Settings", jPanel_Profile_Settings);

        jTabbedPane_Home.addTab("Profile", jTabbedPane_Profile);

        jPanel_Cases_Active.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel_Cases_Active.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane_Cases.addTab("Active", jPanel_Cases_Active);

        jPanel_Cases_Closed.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel_Cases_Closed.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane_Cases.addTab("Closed", jPanel_Cases_Closed);

        jButton_Cases_Open.setText("Open");

        jButton_Cases_Add.setText("Add");

        javax.swing.GroupLayout jPanel_CasesLayout = new javax.swing.GroupLayout(jPanel_Cases);
        jPanel_Cases.setLayout(jPanel_CasesLayout);
        jPanel_CasesLayout.setHorizontalGroup(
            jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Cases)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Cases_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cases_Open)
                .addContainerGap())
        );
        jPanel_CasesLayout.setVerticalGroup(
            jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasesLayout.createSequentialGroup()
                .addComponent(jTabbedPane_Cases, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cases_Open)
                    .addComponent(jButton_Cases_Add))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Cases", jPanel_Cases);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Symptoms"));

        jList1.setModel(new javax.swing.AbstractListModel<String>()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setMinimumSize(new java.awt.Dimension(32, 80));
        jList1.setPreferredSize(new java.awt.Dimension(32, 80));
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane6.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Birth Year");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Gender");

        jYearChooser1.setYear(2000);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");

        jRadioButton2.setText("Female");

        jButton1.setText("Predict");

        jButton3.setText("Open");

        javax.swing.GroupLayout jPanel_PredictLayout = new javax.swing.GroupLayout(jPanel_Predict);
        jPanel_Predict.setLayout(jPanel_PredictLayout);
        jPanel_PredictLayout.setHorizontalGroup(
            jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PredictLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_PredictLayout.createSequentialGroup()
                                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2))
                                    .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel_PredictLayout.setVerticalGroup(
            jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PredictLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Predict", jPanel_Predict);

        jLabel4.setText("City");

        jLabel5.setText("Country");

        jLabel6.setText("State");

        jButton2.setText("Rank");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel_RankingLayout = new javax.swing.GroupLayout(jPanel_Ranking);
        jPanel_Ranking.setLayout(jPanel_RankingLayout);
        jPanel_RankingLayout.setHorizontalGroup(
            jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(jPanel_RankingLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel_RankingLayout.setVerticalGroup(
            jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Ranking", jPanel_Ranking);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel1.setText("Radius (in m):");

        jTextField1.setText("5.0");

        javax.swing.GroupLayout jPanel_NearbyPlacesLayout = new javax.swing.GroupLayout(jPanel_NearbyPlaces);
        jPanel_NearbyPlaces.setLayout(jPanel_NearbyPlacesLayout);
        jPanel_NearbyPlacesLayout.setHorizontalGroup(
            jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NearbyPlacesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NearbyPlacesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_NearbyPlacesLayout.setVerticalGroup(
            jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NearbyPlacesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Nearby Places", jPanel_NearbyPlaces);

        getContentPane().add(jTabbedPane_Home, java.awt.BorderLayout.CENTER);
        jTabbedPane_Home.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        // Background Task
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Cases_Add;
    private javax.swing.JButton jButton_Cases_Open;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Cases;
    private javax.swing.JPanel jPanel_Cases_Active;
    private javax.swing.JPanel jPanel_Cases_Closed;
    private javax.swing.JPanel jPanel_NearbyPlaces;
    private javax.swing.JPanel jPanel_Predict;
    private javax.swing.JPanel jPanel_Profile_Doctor;
    private javax.swing.JPanel jPanel_Profile_Patient;
    private javax.swing.JPanel jPanel_Profile_Settings;
    private javax.swing.JPanel jPanel_Ranking;
    private javax.swing.JPanel jPanel_Search_Case;
    private javax.swing.JPanel jPanel_Search_User;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane_Cases;
    private javax.swing.JTabbedPane jTabbedPane_Home;
    private javax.swing.JTabbedPane jTabbedPane_Profile;
    private javax.swing.JTabbedPane jTabbedPane_Search;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables
}
