/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myproject.pocketclinic;

/**
 *
 * @author Souvik Das
 */
import Priaid.Diagnosis.Client.DiagnosisClient;
import Priaid.Diagnosis.Model.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class JFrame_Home extends javax.swing.JFrame
{
    private List<HealthItem> g_symptom_list;
    private List<HealthItem> g_issue_list;
    
    /**
     * Creates new form JFrame_Home
     */
    public JFrame_Home()
    {        
        initComponents();
        
        try
        {
            // Pre-fetch Medical Data
            g_symptom_list = pocketclinic.dc_obj.loadSymptoms();
            g_issue_list = pocketclinic.dc_obj.loadIssues();
            
            // Prepare Predict - Symptom List
            DefaultListModel jList_Predict_SelectSymptoms_Model = new DefaultListModel();
            jList_Predict_SelectSymptoms.setModel(jList_Predict_SelectSymptoms_Model);
            for(HealthItem x: g_symptom_list)
                jList_Predict_SelectSymptoms_Model.addElement(x);
            
            // Prepare Predict - Output Table Model
            final DefaultTableModel model = (DefaultTableModel) jTable_Predict_Output.getModel();
            model.setNumRows(0);
            final DefaultTableCellRenderer render = new DefaultTableCellRenderer();
            render.setHorizontalAlignment(JLabel.CENTER);
            render.setVerticalAlignment(JLabel.CENTER);
            jTable_Predict_Output.setDefaultRenderer(String.class, render);
            jTable_Predict_Output.setDefaultRenderer(Integer.class, render);
            jTable_Predict_Output.setDefaultRenderer(Double.class, render);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane_Home = new javax.swing.JTabbedPane();
        jTabbedPane_Search = new javax.swing.JTabbedPane();
        jPanel_Search_User = new javax.swing.JPanel();
        jPanel_Search_Case = new javax.swing.JPanel();
        jTabbedPane_Profile = new javax.swing.JTabbedPane();
        jPanel_Profile_Patient = new javax.swing.JPanel();
        jPanel_Profile_Doctor = new javax.swing.JPanel();
        jPanel_Profile_Settings = new javax.swing.JPanel();
        jPanel_Cases = new javax.swing.JPanel();
        jTabbedPane_Cases = new javax.swing.JTabbedPane();
        jPanel_Cases_Active = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_Cases_Closed = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_Cases_Open = new javax.swing.JButton();
        jButton_Cases_Add = new javax.swing.JButton();
        jPanel_Predict = new javax.swing.JPanel();
        jPanel_Predict_SelectSymptoms = new javax.swing.JPanel();
        jScrollPane_Predict_SelectSymptoms = new javax.swing.JScrollPane();
        jList_Predict_SelectSymptoms = new javax.swing.JList<>();
        jPanel_Predicut_Output = new javax.swing.JPanel();
        jScrollPane_Predict_Output = new javax.swing.JScrollPane();
        jTable_Predict_Output = new javax.swing.JTable();
        jLabel_Predict_BirthYear = new javax.swing.JLabel();
        jLabel_Predict_Gender = new javax.swing.JLabel();
        jYearChooser_Predict = new com.toedter.calendar.JYearChooser();
        jRadioButton_Predict_Male = new javax.swing.JRadioButton();
        jRadioButton_Predict_Female = new javax.swing.JRadioButton();
        jButton_Predict_Predict = new javax.swing.JButton();
        jButton_Predict_Open = new javax.swing.JButton();
        jPanel_Ranking = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel_NearbyPlaces = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_Home.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane_Home.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jTabbedPane_Home.setMaximumSize(new java.awt.Dimension(600, 400));
        jTabbedPane_Home.setMinimumSize(new java.awt.Dimension(600, 400));
        jTabbedPane_Home.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jTabbedPane_HomeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Search_UserLayout = new javax.swing.GroupLayout(jPanel_Search_User);
        jPanel_Search_User.setLayout(jPanel_Search_UserLayout);
        jPanel_Search_UserLayout.setHorizontalGroup(
            jPanel_Search_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Search_UserLayout.setVerticalGroup(
            jPanel_Search_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Search.addTab("Search User", jPanel_Search_User);

        javax.swing.GroupLayout jPanel_Search_CaseLayout = new javax.swing.GroupLayout(jPanel_Search_Case);
        jPanel_Search_Case.setLayout(jPanel_Search_CaseLayout);
        jPanel_Search_CaseLayout.setHorizontalGroup(
            jPanel_Search_CaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Search_CaseLayout.setVerticalGroup(
            jPanel_Search_CaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Search.addTab("Search Case", jPanel_Search_Case);

        jTabbedPane_Home.addTab("Search", jTabbedPane_Search);

        javax.swing.GroupLayout jPanel_Profile_PatientLayout = new javax.swing.GroupLayout(jPanel_Profile_Patient);
        jPanel_Profile_Patient.setLayout(jPanel_Profile_PatientLayout);
        jPanel_Profile_PatientLayout.setHorizontalGroup(
            jPanel_Profile_PatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_PatientLayout.setVerticalGroup(
            jPanel_Profile_PatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Patient", jPanel_Profile_Patient);

        javax.swing.GroupLayout jPanel_Profile_DoctorLayout = new javax.swing.GroupLayout(jPanel_Profile_Doctor);
        jPanel_Profile_Doctor.setLayout(jPanel_Profile_DoctorLayout);
        jPanel_Profile_DoctorLayout.setHorizontalGroup(
            jPanel_Profile_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_DoctorLayout.setVerticalGroup(
            jPanel_Profile_DoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Doctor", jPanel_Profile_Doctor);

        javax.swing.GroupLayout jPanel_Profile_SettingsLayout = new javax.swing.GroupLayout(jPanel_Profile_Settings);
        jPanel_Profile_Settings.setLayout(jPanel_Profile_SettingsLayout);
        jPanel_Profile_SettingsLayout.setHorizontalGroup(
            jPanel_Profile_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        jPanel_Profile_SettingsLayout.setVerticalGroup(
            jPanel_Profile_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        jTabbedPane_Profile.addTab("Settings", jPanel_Profile_Settings);

        jTabbedPane_Home.addTab("Profile", jTabbedPane_Profile);

        jPanel_Cases_Active.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel_Cases_Active.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane_Cases.addTab("Active", jPanel_Cases_Active);

        jPanel_Cases_Closed.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel_Cases_Closed.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane_Cases.addTab("Closed", jPanel_Cases_Closed);

        jButton_Cases_Open.setText("Open");

        jButton_Cases_Add.setText("Add");

        javax.swing.GroupLayout jPanel_CasesLayout = new javax.swing.GroupLayout(jPanel_Cases);
        jPanel_Cases.setLayout(jPanel_CasesLayout);
        jPanel_CasesLayout.setHorizontalGroup(
            jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Cases)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Cases_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Cases_Open)
                .addContainerGap())
        );
        jPanel_CasesLayout.setVerticalGroup(
            jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CasesLayout.createSequentialGroup()
                .addComponent(jTabbedPane_Cases, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Cases_Open)
                    .addComponent(jButton_Cases_Add))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Cases", jPanel_Cases);

        jPanel_Predict_SelectSymptoms.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Symptoms"));
        jPanel_Predict_SelectSymptoms.setLayout(new java.awt.BorderLayout());

        jScrollPane_Predict_SelectSymptoms.setViewportView(jList_Predict_SelectSymptoms);

        jPanel_Predict_SelectSymptoms.add(jScrollPane_Predict_SelectSymptoms, java.awt.BorderLayout.CENTER);

        jPanel_Predicut_Output.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel_Predicut_Output.setLayout(new java.awt.BorderLayout());

        jTable_Predict_Output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Disease", "Accuracy %"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable_Predict_Output.setColumnSelectionAllowed(true);
        jScrollPane_Predict_Output.setViewportView(jTable_Predict_Output);
        jTable_Predict_Output.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel_Predicut_Output.add(jScrollPane_Predict_Output, java.awt.BorderLayout.CENTER);

        jLabel_Predict_BirthYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Predict_BirthYear.setText("Birth Year");

        jLabel_Predict_Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_Predict_Gender.setText("Gender");

        jYearChooser_Predict.setYear(2000);

        jRadioButton_Predict_Male.setSelected(true);
        jRadioButton_Predict_Male.setText("Male");

        jRadioButton_Predict_Female.setText("Female");

        jButton_Predict_Predict.setText("Predict");
        jButton_Predict_Predict.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton_Predict_PredictActionPerformed(evt);
            }
        });

        jButton_Predict_Open.setText("Open");

        javax.swing.GroupLayout jPanel_PredictLayout = new javax.swing.GroupLayout(jPanel_Predict);
        jPanel_Predict.setLayout(jPanel_PredictLayout);
        jPanel_PredictLayout.setHorizontalGroup(
            jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PredictLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_PredictLayout.createSequentialGroup()
                                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Predict_BirthYear)
                                    .addComponent(jLabel_Predict_Gender))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_Predict_Male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_Predict_Female))
                                    .addComponent(jYearChooser_Predict, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel_Predict_SelectSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Predicut_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addComponent(jButton_Predict_Predict)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Predict_Open)))
                .addContainerGap())
        );
        jPanel_PredictLayout.setVerticalGroup(
            jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PredictLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_PredictLayout.createSequentialGroup()
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Predict_BirthYear)
                            .addComponent(jYearChooser_Predict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_Predict_Male)
                            .addComponent(jRadioButton_Predict_Female)
                            .addComponent(jLabel_Predict_Gender))
                        .addGap(7, 7, 7)
                        .addComponent(jPanel_Predict_SelectSymptoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_Predicut_Output, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PredictLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Predict_Predict)
                    .addComponent(jButton_Predict_Open))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Predict", jPanel_Predict);

        jLabel4.setText("City");

        jLabel5.setText("Country");

        jLabel6.setText("State");

        jButton2.setText("Rank");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel_RankingLayout = new javax.swing.GroupLayout(jPanel_Ranking);
        jPanel_Ranking.setLayout(jPanel_RankingLayout);
        jPanel_RankingLayout.setHorizontalGroup(
            jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(jPanel_RankingLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel_RankingLayout.setVerticalGroup(
            jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_RankingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel_RankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Ranking", jPanel_Ranking);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel1.setText("Radius (in m):");

        jTextField1.setText("5.0");

        javax.swing.GroupLayout jPanel_NearbyPlacesLayout = new javax.swing.GroupLayout(jPanel_NearbyPlaces);
        jPanel_NearbyPlaces.setLayout(jPanel_NearbyPlacesLayout);
        jPanel_NearbyPlacesLayout.setHorizontalGroup(
            jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NearbyPlacesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NearbyPlacesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_NearbyPlacesLayout.setVerticalGroup(
            jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NearbyPlacesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_NearbyPlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jTabbedPane_Home.addTab("Nearby Places", jPanel_NearbyPlaces);

        getContentPane().add(jTabbedPane_Home, java.awt.BorderLayout.CENTER);
        jTabbedPane_Home.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Predict_PredictActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton_Predict_PredictActionPerformed
    {//GEN-HEADEREND:event_jButton_Predict_PredictActionPerformed
        List temp = jList_Predict_SelectSymptoms.getSelectedValuesList();
        ArrayList<Integer> selected_symptoms = new ArrayList<Integer>();
        for(Object x: temp)
            selected_symptoms.add(((HealthItem) x).ID);
        Gender selected_gender = jRadioButton_Predict_Male.isSelected() ? Gender.Male : Gender.Female;
        Integer selected_year = jYearChooser_Predict.getValue();
        try
        {
            List<HealthDiagnosis> temp2 =
                pocketclinic.dc_obj.loadDiagnosis(selected_symptoms, selected_gender, selected_year);
            DefaultTableModel model = (DefaultTableModel)jTable_Predict_Output.getModel();
            model.setNumRows(0);
            for(HealthDiagnosis x: temp2)
            {
                model.addRow
                (
                    new Object[]
                    {
                        x.Issue,
                        x.Issue.Accuracy
                    }
                );
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton_Predict_PredictActionPerformed

    private void jTabbedPane_HomeStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jTabbedPane_HomeStateChanged
    {//GEN-HEADEREND:event_jTabbedPane_HomeStateChanged
        switch(jTabbedPane_Home.getSelectedIndex())
        {
            case 0:
            {
                
            } break;
            case 1:
            {
                
            } break;
            case 2:
            {
                
            } break;
            case 3:
            {
                
            } break;
            case 4:
            {

            } break;
            case 5:
            {
                
            } break;
        }
    }//GEN-LAST:event_jTabbedPane_HomeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        // Background Task
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Cases_Add;
    private javax.swing.JButton jButton_Cases_Open;
    private javax.swing.JButton jButton_Predict_Open;
    private javax.swing.JButton jButton_Predict_Predict;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Predict_BirthYear;
    private javax.swing.JLabel jLabel_Predict_Gender;
    private javax.swing.JList<String> jList_Predict_SelectSymptoms;
    private javax.swing.JPanel jPanel_Cases;
    private javax.swing.JPanel jPanel_Cases_Active;
    private javax.swing.JPanel jPanel_Cases_Closed;
    private javax.swing.JPanel jPanel_NearbyPlaces;
    private javax.swing.JPanel jPanel_Predict;
    private javax.swing.JPanel jPanel_Predict_SelectSymptoms;
    private javax.swing.JPanel jPanel_Predicut_Output;
    private javax.swing.JPanel jPanel_Profile_Doctor;
    private javax.swing.JPanel jPanel_Profile_Patient;
    private javax.swing.JPanel jPanel_Profile_Settings;
    private javax.swing.JPanel jPanel_Ranking;
    private javax.swing.JPanel jPanel_Search_Case;
    private javax.swing.JPanel jPanel_Search_User;
    private javax.swing.JRadioButton jRadioButton_Predict_Female;
    private javax.swing.JRadioButton jRadioButton_Predict_Male;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane_Predict_Output;
    private javax.swing.JScrollPane jScrollPane_Predict_SelectSymptoms;
    private javax.swing.JTabbedPane jTabbedPane_Cases;
    private javax.swing.JTabbedPane jTabbedPane_Home;
    private javax.swing.JTabbedPane jTabbedPane_Profile;
    private javax.swing.JTabbedPane jTabbedPane_Search;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable_Predict_Output;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private com.toedter.calendar.JYearChooser jYearChooser_Predict;
    // End of variables declaration//GEN-END:variables
}
